#!/usr/bin/env bash

set -Eeuo pipefail

function rm_if_exists {
  file=$1
  if [ "$(ls "${file}")" ]; then
    echo "Removing ${file}"
    rm -rf "${file}"
  fi
}

function symlink {
  target=$1
  link_name=$2
  ln -s "${HOME}/.dotfiles/${target}" "${link_name}"
  ls -lhart "${link_name}"
}

function gitconf {
  echo "Setting up git..."
  rm_if_exists "${HOME}/.gitconfig"
  rm_if_exists "${HOME}/.gitignore"
  symlink "git/gitignore" "${HOME}/.gitignore"
  symlink "git/gitconfig" "${HOME}/.gitconfig"
}

function alacritty {
  alacritty_path="${HOME}/.config/alacritty.yml"
  echo "Setting up alacritty..."
  rm_if_exists "${alacritty_path}"
  symlink "alacritty/alacritty.yml" "${alacritty_path}"
}

function tmux {
  echo "Setting up tmux..."
  rm_if_exists "${HOME}/.tmux.conf"
  symlink "tmux/tmux.conf" "${HOME}/.tmux.conf"
}

function neovim {
  echo "Setting up neovim..."
  neovim_path="${HOME}/.config/nvim"
  rm -rfv "${neovim_path}"
  rm -rfv "${HOME}/.local/share/nvim"
  rm -rfv "${HOME}/.cache/nvim"
  git clone https://github.com/NvChad/NvChad "${neovim_path}" --depth 1
  symlink "nvchad/custom/" "${neovim_path}/lua/custom"
}

function zsh {
  echo "Setting up oh-my-zsh..."
  rm_if_exists "${HOME}/.zshrc"
  symlink "/zsh/zshrc" "${HOME}/.zshrc"
}

function zsh_vi_mode {
  echo "Setting up zsh-vi-mode..."
  #custom_zsh=${HOME}/.dotfiles/zsh
  rm_if_exists "${ZSH_CUSTOM}/plugins/zsh-vi-mode"
  git clone https://github.com/jeffreytse/zsh-vi-mode.git \
    "${ZSH_CUSTOM}/plugins/zsh-vi-mode"
}

function powerlevel10k {
  echo "Setting up powerlevel10k..."
  # custom_zsh=${HOME}/.dotfiles/zsh/custom
  rm_if_exists "${ZSH_CUSTOM}/themes/powerlevel10k"
  rm_if_exists "${HOME}/.p10k.zsh"
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git \
    "${ZSH_CUSTOM}/themes/powerlevel10k"
  symlink "/zsh/p10k.zsh" "${HOME}/.p10k.zsh"
}

function fzf {
  echo "Setting up fzf..."
  rm_if_exists "${HOME}/.fzf"
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  ~/.fzf/install
}

usage() {
  cat <<EOF
Usage: $(basename "${BASH_SOURCE[0]}") [-h] [-d] [-f] -p param_value arg1 [arg2...]
Script description here.
Available options:
-h, --help      Print this help and exit
-d, --debug     Print script debug info
-f, --flag      Some flag description
-p, --param     Some param description
EOF
exit
}

function main {
  echo "Setting up dotfiles..."
  gitconf
  alacritty
  tmux
  neovim
  zsh
  zsh_vi_mode
  powerlevel10k
  fzf
}

if [[ "${1-}" =~ ^-*h(elp)?$ ]]; then
  usage
fi

main "$@"
