#!/usr/bin/env bash

gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled false
export PROTON_ENABLE_HDR=1
gnome-session-inhibit --inhibit idle gamescope --hide-cursor-delay 1000 -e -W 1920 -H 1080 -r 60 -f -F fsr --hdr-enabled --backend wayland -- steam
