#!/usr/bin/env bash

export PROTON_ENABLE_HDR=1
export DXVK_HDR=1
export ENABLE_HDR_WSI=1

gamescope --mangoapp -e -W 1920 -H 1080 -r 60 -f -F fsr \
  --hdr-enabled --hdr-sdr-content-nits 180 \
  --backend drm \
  -- steam -steamos3
